### ISSUE TITLE
Browser request - Comodo Dragon

### ISSUE THREAD

**Issue by fleapower** [arthuredelstein/privacytests.org#102]
Found your site today - very helpful info!

I know you said you are hoping to add additional browsers to your tests.  Request you add Comodo Dragon.  Thanks!

**Comment by IronMaltese** [comment]
https://www.comodo.com/home/browsers-toolbars/browser.php just a note that this browser is freeware, which is not open source

**Comment by fleapower** [comment]
Thanks.  Didn't realize your tests were only for open-source software.

**Comment by IronMaltese** [comment]
Chrome isn't open source and it's included so you can reopen this issue, I just wanted to add it as a note

**Comment by fleapower** [comment]
👍

**Comment by arthuredelstein** [comment]
Yes, I'm open to testing browsers that are not open source. The tests themselves are open-source.
