### ISSUE TITLE
Mull browser

### ISSUE THREAD

**Issue by SkewedZeppelin** [arthuredelstein/privacytests.org#85]
Mull browser is a compiled from source build of Firefox for Android with proprietary blobs removed.
It also includes a modified arkenfox.js by default.
I've maintained it since 2017: https://divestos.org/misc/ffa-dates.txt
Source code: https://github.com/divested-mobile/mull-fenix

You can download it from either my repo or the official F-Droid repo:
https://divestos.org/fdroid/official/index-v1.json, https://divestos.org/fdroid/official/us.spotco.fennec_dos_2961121.apk
https://f-droid.org/packages/us.spotco.fennec_dos/, https://f-droid.org/repo/us.spotco.fennec_dos_2952020.apk

Anything I can do that'd make it easier to add, please let me know.
Thanks

**Comment by arthuredelstein** [comment]
Thank you for the suggestion! I will look into it.

**Comment by helpthemfix** [comment]
Any updates on Mull? I am eagerly waiting for your tests on it.

**Comment by SkewedZeppelin** [comment]
@arthuredelstein 
Thank you!
:rocket:

**Comment by MaxsimLionel** [comment]
Would really love to see mull on the test site!
